CREATE TABLE IF NOT EXISTS zakaz (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    summa VARCHAR(255),
    address_zakaz VARCHAR(255),
    book_id INT,
    FOREIGN KEY(book_id) REFERENCES book(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


